symptoms = [
    ('CA', 'Cansaço'),
    ('CN', 'Congestão nasal'),
    ('DI', 'Diarreia'),
    ('SB', 'Dificuldade respiratória'),
    ('ST', 'Dor de garganta'),
    ('DC', 'Dor de cabeça'),
    ('AP', 'Dores no corpo'),
    ('FA', 'Falta de apetite'), # famoso fastio
    ('FV', 'Febre'),
    ('RN', 'Nariz escorrendo'),
    ('NA', 'Náusea'),
    ('TP', 'Tosse produtiva'),
    ('TS', 'Tosse seca'),
    ('VO', 'Vômitos'),
]

intensities = [
    ('', 'Não apresenta'),
    ('L', 'Leve'),
    ('M', 'Moderada'),
    ('H', 'Grave'),
]

genders = [
    ('F', 'Feminino'),
    ('M', 'Masculino'),
    ('N', 'Não quer declarar')
]

address_types = [
    ('HM', 'Residencial'),
    ('WK', 'Trabalho'),
    ('OT', 'Outro'),
]

# drugs = [
#     ('', 'Anti hipertensivo'),
#     ('', 'Imunossupressores'),
#     ('', 'Anti diabéticos'),
#     ('', 'Antibióticos'),
#     ('', 'Corticoide'),
#     ('', 'Anti inflamatório')
# ]

comorbidities = [
    ('Y', 'Artrite reumatóide'),
    ('A', 'Asma'),
    ('C', 'Bronquite crônica'),
    ('N', 'Câncer'),
    ('E', 'Demência'),
    ('D', 'Diabetes'),
    ('H', 'Doença cardíacas'),
    ('L', 'Doença crônica no fígado'),
    ('R', 'Doença renal crônica'),
    ('W', 'Doenças reumáticas'),
    ('P', 'Doença pulmonar crônica'),
    ('I', 'Imunosuprimido'),
    ('T', 'Hipertensão'),
    ('V', 'HIV+'),
    ('B', 'Obesidade'),
    ('U', 'Portador de Lúpus'),
]

countries = [
    ('AFE', 'Afeganistão'),
    ('AFR', 'África do Sul'),
    ('AUS', 'Áustria'),
    ('ALB', 'Albânia'),
    ('ALE', 'Alemanha'),
    ('AND', 'Andorra'),
    ('ANG', 'Angola'),
    ('ANT', 'Antígua e Barbuda'),
    ('ARG', 'Argentina'),
    ('ARL', 'Argélia'),
    ('ARM', 'Armênia'),
    ('ARA', 'Arábia Saudita'),
    ('AUL', 'Austrália'),
    ('AZE', 'Azerbaijão'),
    ('BAH', 'Bahamas'),
    ('BAN', 'Bangladesh'),
    ('BAR', 'Barbados'),
    ('BAM', 'Barém'),
    ('BEL', 'Belize'),
    ('BEN', 'Benin'),
    ('BIE', 'Bielorrússia'),
    ('BOL', 'Bolívia'),
    ('BOT', 'Botsuana'),
    ('BRA', 'Brasil'),
    ('BRU', 'Brunei Darussalam'),
    ('BUL', 'Bulgária'),
    ('BUR', 'Burkina Faso'),
    ('BUD', 'Burundi'),
    ('BUT', 'Butão'),
    ('BEG', 'Bélgica'),
    ('BOS', 'Bósnia e Herzegovina'),
    ('CAB', 'Cabo Verde'),
    ('CAM', 'Camarões'),
    ('CAJ', 'Camboja'),
    ('CAN', 'Canadá'),
    ('CAT', 'Catar'),
    ('CAZ', 'Cazaquistão'),
    ('CHA', 'Chade'),
    ('CHL', 'Chile'),
    ('CHI', 'China'),
    ('CHP', 'Chipre'),
    ('CIN', 'Cingapura'),
    ('COL', 'Colômbia'),
    ('COM', 'Comores'),
    ('CON', 'Congo'),
    ('COS', 'Costa Rica'),
    ('COT', 'Costa do Marfim'),
    ('CRO', 'Croácia'),
    ('CUB', 'Cuba'),
    ('CZE', 'Czechia'),
    ('DIN', 'Dinamarca'),
    ('DJI', 'Djibuti'),
    ('DOM', 'Dominica'),
    ('EGI', 'Egito'),
    ('ELS', 'El Salvador'),
    ('EMI', 'Emirados Árabes Unidos'),
    ('EQU', 'Equador'),
    ('ERI', 'Eritreia'),
    ('ESL', 'Eslováquia'),
    ('ESV', 'Eslovênia'),
    ('ESP', 'Espanha'),
    ('EST', 'Estados Unidos da America'),
    ('ESN', 'Estônia'),
    ('ESW', 'Eswatini'),
    ('ETI', 'Etiópia'),
    ('FED', 'Federação Russa'),
    ('FIJ', 'Fiji'),
    ('FIL', 'Filipinas'),
    ('FIN', 'Finlândia'),
    ('FRA', 'França'),
    ('GAB', 'Gabão'),
    ('GAN', 'Gana'),
    ('GAM', 'Gâmbia'),
    ('GEO', 'Geórgia'),
    ('GRA', 'Granada'),
    ('GRÉ', 'Grécia'),
    ('GUA', 'Guatemala'),
    ('GUI', 'Guiana'),
    ('GUN', 'Guiné'),
    ('GUE', 'Guiné Equatorial'),
    ('GUB', 'Guiné-Bissau'),
    ('HAI', 'Haiti'),
    ('HON', 'Honduras'),
    ('HUN', 'Hungria'),
    ('IND', 'Índia'),
    ('ILC', 'Ilhas Cook'),
    ('ILM', 'Ilhas Marshall'),
    ('ILS', 'Ilhas Salomão'),
    ('INN', 'Indonésia'),
    ('IRQ', 'Iraque'),
    ('IRL', 'Irlanda'),
    ('IRA', 'Irã'),
    ('ISL', 'Islândia'),
    ('ISR', 'Israel'),
    ('ITA', 'Itália'),
    ('IEM', 'Iémen'),
    ('JAM', 'Jamaica'),
    ('JAP', 'Japão'),
    ('JOR', 'Jordânia'),
    ('KIR', 'Kiribati'),
    ('KUW', 'Kuwait'),
    ('LES', 'Lesoto'),
    ('LET', 'Letônia'),
    ('LIB', 'Libéria'),
    ('LIT', 'Lituânia'),
    ('LUX', 'Luxemburgo'),
    ('LIB', 'Líbano'),
    ('LIA', 'Líbia'),
    ('MAC', 'Macedônia do Norte'),
    ('MAD', 'Madagáscar'),
    ('MAW', 'Malawi'),
    ('MAD', 'Maldivas'),
    ('MAL', 'Mali'),
    ('MAT', 'Malta'),
    ('MAS', 'Malásia'),
    ('MAR', 'Marrocos'),
    ('MAU', 'Mauritânia'),
    ('MAR', 'Maurícia'),
    ('MIC', 'Micronésia'),
    ('MON', 'Mongólia'),
    ('MOT', 'Montenegro'),
    ('MOC', 'Moçambique'),
    ('MYA', 'Myanmar'),
    ('MEX', 'México'),
    ('MOO', 'Mônaco'),
    ('NAM', 'Namíbia'),
    ('NAU', 'Nauru'),
    ('NEP', 'Nepal'),
    ('NIC', 'Nicarágua'),
    ('NIG', 'Nigéria'),
    ('NIG', 'Níger'),
    ('NIU', 'Niue'),
    ('NOR', 'Noruega'),
    ('NOV', 'Nova Zelândia'),
    ('OMA', 'Omã'),
    ('PAL', 'Palau'),
    ('PAN', 'Panamá'),
    ('PAP', 'Papua Nova Guiné'),
    ('PAQ', 'Paquistão'),
    ('PAR', 'Paraguai'),
    ('PAI', 'Países Baixos'),
    ('PER', 'Peru'),
    ('POL', 'Polônia'),
    ('POR', 'Portugal'),
    ('QUI', 'Quirguistão'),
    ('QUE', 'Quênia'),
    ('REI', 'Reino Unido'),
    ('REP', 'República Centro-Africana'),
    ('RED', 'República Democrática Popular do Laos'),
    ('RDC', 'República Democrática do Congo'),
    ('RDM', 'República Dominicana'),
    ('RPD', 'República Popular Democrática da Coreia'),
    ('RET', 'República Togolesa'),
    ('RUT', 'República Unida da Tanzânia'),
    ('RCA', 'República da Coreia'),
    ('REM', 'República da Moldávia'),
    ('RAS', 'República Árabe da Síria'),
    ('ROM', 'Romênia'),
    ('RUA', 'Ruanda'),
    ('SAM', 'Samoa'),
    ('SMO', 'San Marino'),
    ('SAN', 'Santa Lúcia'),
    ('SEN', 'Senegal'),
    ('SER', 'Serra Leoa'),
    ('SEY', 'Seychelles'),
    ('SOM', 'Somália'),
    ('SRI', 'Sri Lanka'),
    ('SUD', 'Sudão'),
    ('SUS', 'Sudão do Sul'),
    ('SUR', 'Suriname'),
    ('SUE', 'Suécia'),
    ('SUI', 'Suíça'),
    ('SAC', 'São Cristóvão e Nevis'),
    ('SAT', 'São Tomé e Príncipe'),
    ('SAV', 'São Vicente e Granadinas'),
    ('SEV', 'Sérvia'),
    ('TAI', 'Tailândia'),
    ('TAJ', 'Tajiquistão'),
    ('TIM', 'Timor-Leste'),
    ('TON', 'Tonga'),
    ('TRI', 'Trindade e Tobago'),
    ('TUN', 'Tunísia'),
    ('TUR', 'Turquemenistão'),
    ('TUQ', 'Turquia'),
    ('TUV', 'Tuvalu'),
    ('UCR', 'Ucrânia'),
    ('UGA', 'Uganda'),
    ('URU', 'Uruguai'),
    ('USB', 'Usbequistão'),
    ('VAN', 'Vanuatu'),
    ('VEN', 'Venezuela'),
    ('VIE', 'Vietnã'),
    ('ZIM', 'Zimbábue'),
    ('ZAM', 'Zâmbia'),
]

exposure = [
    ('confirmed_cases', 'Contato com casos confirmados'),
    ('suspect_cases', 'Contato com casos suspeitos'),
    ('foreign', 'Contato com pessoas que estiveram em locais com casos confirmados'),
]

results = [
    ('SR', 'Sem resposta'),
    ('PO', 'Positivo'),
    ('NE', 'Negativo'),
]

status = (
    ('N', 'Normal'),
    ('T', 'Testado'),
    ('S', 'Suspeito'),
    ('C', 'Confirmado'),
    ('M', 'Morto'),
    ('I', 'Imune'),
    ('H', 'Hospitalizado'),
    ('U', 'UTI')
)

action_choices = (
    ('C','CREATE'),
    ('D','DELETE'),
    ('U','UPDATE'),
)

model_choices = (
    ('PR','PROFILE'),
    ('AD','ADDRESS'),
    ('MO','MONITORING'),
    ('SY','SYMPTOM'),
    ('TR','TRIP'),
    ('RE','REQUEST'),
    ('HC', 'HEALTH CARE STATUS')
)

cities = (
    ('Água Branca','Água Branca'),
    ('Anadia','Anadia'),
    ('Arapiraca','Arapiraca'),
    ('Atalaia', 'Atalaia'),
    ('Barra de Santo Antônio','Barra de Santo Antônio'),
    ('Barra de São Miguel','Barra de São Miguel'),
    ('Batalha','Batalha'),
    ('Belém','Belém'),
    ('Belo Monte','Belo Monte'),
    ('Boca da Mata','Boca da Mata'),
    ('Branquinha','Branquinha'),
    ('Cacimbinhas','Cacimbinhas'),
    ('Cajueiro','Cajueiro'),
    ('Campestre','Campestre'),
    ('Campo Alegre','Campo Alegre'),
    ('Campo Grande','Campo Grande'),
    ('Canapí','Canapí'),
    ('Capela','Capela'),
    ('Carneiros','Carneiros'),
    ('Chã Preta','Chã Preta'),
    ('Coité do Nóia','Coité do Nóia'),
    ('Colônia Leopoldina','Colônia Leopoldina'),
    ('Coqueiro Seco','Coqueiro Seco'),
    ('Coruripe','Coruripe'),
    ('Craíbas','Craíbas'),
    ('Delmiro Gouveia','Delmiro Gouveia'),
    ('Dois Riachos','Dois Riachos'),
    ('Estrela de Alagoas','Estrela de Alagoas'),
    ('Feira Grande','Feira Grande'),
    ('Feliz Deserto','Feliz Deserto'),
    ('Flexeiras','Flexeiras'),
    ('Girau do Ponciano','Girau do Ponciano'),
    ('Ibateguara','Ibateguara'),
    ('Igací','Igací'),
    ('Igreja Nova','Igreja Nova'),
    ('Inhapí','Inhapí'),
    ('Jacaré dos Homens','Jacaré dos Homens'),
    ('Jacuípe','Jacuípe'),
    ('Japaratinga','Japaratinga'),
    ('Jaramataia','Jaramataia'),
    ('Jequiá da Praia','Jequiá da Praia'),
    ('Joaquim Gomes','Joaquim Gomes'),
    ('Jundiá','Jundiá'),
    ('Junqueiro','Junqueiro'),
    ('Lagoa da Canoa','Lagoa da Canoa'),
    ('Limoeiro de Anadia','Limoeiro de Anadia'),
    ('Maceió','Maceió'),
    ('Major Isidoro','Major Isidoro'),
    ('Mar Vermelho','Mar Vermelho'),
    ('Maragogi','Maragogi'),
    ('Maravilha','Maravilha'),
    ('Marechal Deodoro','Marechal Deodoro'),
    ('Maribondo','Maribondo'),
    ('Mata Grande','Mata Grande'),
    ('Matriz de Camaragibe','Matriz de Camaragibe'),
    ('Messias','Messias'),
    ('Minador do Negrão','Minador do Negrão'),
    ('Monteirópolis','Monteirópolis'),
    ('Murici','Murici'),
    ('Novo Lino','Novo Lino'),
    ('Olho D’Água das Flôres','Olho D’Água das Flôres'),
    ('Olho D’Água do Casado','Olho D’Água do Casado'),
    ('Olho D’Água Grande','Olho D’Água Grande'),
    ('Olivença','Olivença'),
    ('Ouro Branco','Ouro Branco'),
    ('Palestina','Palestina'),
    ('Palmeira dos Índios','Palmeira dos Índios'),
    ('Pão de Açucar','Pão de Açucar'),
    ('Pariconha','Pariconha'),
    ('Paripueira','Paripueira'),
    ('Passo de Camaragibe','Passo de Camaragibe'),
    ('Paulo Jacinto','Paulo Jacinto'),
    ('Penedo','Penedo'),
    ('Piaçabuçu','Piaçabuçu'),
    ('Pilar','Pilar'),
    ('Pindoba','Pindoba'),
    ('Piranhas','Piranhas'),
    ('Poço das Trincheiras','Poço das Trincheiras'),
    ('Porto Calvo','Porto Calvo'),
    ('Porto de Pedras','Porto de Pedras'),
    ('Porto Real do Colégio','Porto Real do Colégio'),
    ('Quebrangulo','Quebrangulo'),
    ('Rio Largo','Rio Largo'),
    ('Roteiro','Roteiro'),
    ('Santa Luzia do Norte','Santa Luzia do Norte'),
    ('Santana do Ipanema','Santana do Ipanema'),
    ('Santana do Mundaú','Santana do Mundaú'),
    ('São Brás','São Brás'),
    ('São José da Laje','São José da Laje'),
    ('São José da Tapera','São José da Tapera'),
    ('São Luiz do Quitunde','São Luiz do Quitunde'),
    ('São Miguel dos Campos','São Miguel dos Campos'),
    ('São Miguel dos Milagres','São Miguel dos Milagres'),
    ('São Sebastião','São Sebastião'),
    ('Satuba','Satuba'),
    ('Senador Rui Palmeira','Senador Rui Palmeira'),
    ('Tanque D’Arca','Tanque D’Arca'),
    ('Taquarana','Taquarana'),
    ('Teotônio Vilela','Teotônio Vilela'),
    ('Traipu','Traipu')
)
