# Generated by Django 2.2.3 on 2020-03-26 23:45

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
