# Generated by Django 3.0.4 on 2020-03-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighbourhood',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro'),
        ),
    ]
