# Generated by Django 3.0.4 on 2020-03-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200323_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, choices=[('ARA', 'Arapiraca'), ('MCZ', 'Maceió'), ('MDO', 'Marechal Deodoro'), ('PEN', 'Penedo'), ('UPM', 'União dos Palmares')], default='', max_length=3, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighbourhood',
            field=models.CharField(blank=True, choices=[('BB', 'Benedito Bentes'), ('CU', 'Cidade Universitária'), ('GC', 'Graciliano Ramos'), ('JA', 'Jaraguá'), ('JC', 'Jacintinho'), ('JT', 'Jatiúca'), ('MG', 'Mangabeiras'), ('PV', 'Ponta Verde')], default='', max_length=2, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='address',
            name='people',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Quantidade de pessoas'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(blank=True, choices=[('HM', 'Residencial'), ('WK', 'Trabalho')], default='', max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='type',
            field=models.CharField(blank=True, choices=[('H', 'Doença cardíacas'), ('T', 'Hipertensão'), ('D', 'Diabetes'), ('E', 'Demência'), ('C', 'Bronquite crônica'), ('N', 'Câncer'), ('L', 'Doença crônica no fígado'), ('R', 'Doença renal crônica'), ('A', 'Asma'), ('P', 'Doença pulmonar crônica'), ('R', 'Doenças reumáticas'), ('O', 'Outras doenças')], max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], default='', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Número de telefone'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='intensity',
            field=models.CharField(choices=[('L', 'Leve'), ('M', 'Moderada'), ('H', 'Grave')], default='', max_length=1, verbose_name='Intensidade'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='onset',
            field=models.DateField(blank=True, null=True, verbose_name='Data do surgimento'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptom',
            field=models.CharField(choices=[('TR', 'Cansaço'), ('DI', 'Diarreia'), ('SB', 'Dificuldade respiratória'), ('ST', 'Dor de garganta'), ('AP', 'Dores no corpo'), ('FV', 'Febre'), ('DC', 'Tosse'), ('RN', 'Nariz escorrendo'), ('DI', 'Náusea')], default='', max_length=2, verbose_name='Tipo de sintoma'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.CharField(blank=True, choices=[('CHN', 'China'), ('BRA', 'Brasil'), ('ESP', 'Espanha'), ('USA', 'Estados Unidos'), ('ITA', 'Itália')], default='', max_length=3, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Ida'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Volta'),
        ),
    ]
