# Generated by Django 3.0.4 on 2020-03-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200324_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account',
        ),
        migrations.AddField(
            model_name='profile',
            name='oxygen',
            field=models.BooleanField(blank=True, default=False, verbose_name='Já precisou de oxigênio'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(blank=True, choices=[('HM', 'Residencial'), ('WK', 'Trabalho'), ('OT', 'Outro')], default='', max_length=2, verbose_name='Tipo'),
        ),
    ]
