# Generated by Django 3.0.4 on 2020-03-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200323_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome da mãe'),
        ),
    ]
