# Generated by Django 3.0.4 on 2020-03-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_mother_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
