# Generated by Django 2.2.3 on 2020-03-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmado')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome completo')),
                ('mother_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome da mãe')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('sus_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cartão do SUS')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], default='', max_length=1, verbose_name='Sexo')),
                ('phone_number', models.CharField(blank=True, default='', max_length=11, verbose_name='Número de telefone')),
                ('vaccinated', models.BooleanField(blank=True, default=False, verbose_name='Tomou vacina da gripe em 2020')),
                ('oxygen', models.BooleanField(blank=True, default=False, verbose_name='Precisou de oxigênio recentemente')),
                ('diabetes', models.BooleanField(blank=True, default=False, verbose_name='Diabetes')),
                ('heart_diseases', models.BooleanField(blank=True, default=False, verbose_name='Doenças cardíacas')),
                ('hypertension', models.BooleanField(blank=True, default=False, verbose_name='Hipertensão')),
                ('dementia', models.BooleanField(blank=True, default=False, verbose_name='Demência')),
                ('bronchitis', models.BooleanField(blank=True, default=False, verbose_name='Bronquite crônica')),
                ('cancer', models.BooleanField(blank=True, default=False, verbose_name='Câncer')),
                ('chronic_liver_disease', models.BooleanField(blank=True, default=False, verbose_name='Doença crônica no fígado')),
                ('chronic_kidney_disease', models.BooleanField(blank=True, default=False, verbose_name='Doença renal crônica')),
                ('asthma', models.BooleanField(blank=True, default=False, verbose_name='Asma')),
                ('chronic_lung_disease', models.BooleanField(blank=True, default=False, verbose_name='Doença pulmonar crônica')),
                ('rheumatic_diseases', models.BooleanField(blank=True, default=False, verbose_name='Doenças reumáticas')),
                ('obesity', models.BooleanField(blank=True, default=False, verbose_name='Obesidade')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(blank=True, default=None, null=True, verbose_name='Ida')),
                ('return_date', models.DateField(blank=True, default=None, null=True, verbose_name='Volta')),
                ('country', models.CharField(choices=[('CHN', 'China'), ('BRA', 'Brasil'), ('ESP', 'Espanha'), ('USA', 'Estados Unidos'), ('ITA', 'Itália')], default='', max_length=3, verbose_name='País')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(choices=[('TR', 'Cansaço'), ('DI', 'Diarreia'), ('SB', 'Dificuldade respiratória'), ('ST', 'Dor de garganta'), ('AP', 'Dores no corpo'), ('FV', 'Febre'), ('DC', 'Tosse'), ('RN', 'Nariz escorrendo'), ('DI', 'Náusea'), ('OT', 'Outro')], default='', max_length=2, verbose_name='Tipo de sintoma')),
                ('intensity', models.CharField(blank=True, choices=[('', 'Não apresenta'), ('L', 'Leve'), ('M', 'Moderada'), ('H', 'Grave')], default='L', max_length=1, verbose_name='Intensidade')),
                ('onset', models.DateField(blank=True, null=True, verbose_name='Data do surgimento')),
                ('monitoring', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Monitoring')),
            ],
        ),
        migrations.AddField(
            model_name='monitoring',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Profile'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('HM', 'Residencial'), ('WK', 'Trabalho'), ('OT', 'Outro')], default='', max_length=2, verbose_name='Tipo')),
                ('postal_code', models.CharField(blank=True, default='', max_length=8, verbose_name='CEP')),
                ('neighbourhood', models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro')),
                ('street_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Logradouro')),
                ('number', models.PositiveIntegerField(blank=True, default=0, verbose_name='Número')),
                ('complement', models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('people', models.PositiveIntegerField(blank=True, default=1, verbose_name='Quantidade de pessoas')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Profile')),
            ],
        ),
    ]
