# Generated by Django 2.2.3 on 2020-03-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Idade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rg',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoke',
            field=models.BooleanField(blank=True, default=False, verbose_name='Já fumou/fuma?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('ND', 'Não quer declarar')], default='', max_length=1, verbose_name='Sexo'),
        ),
    ]
