# Generated by Django 3.0.4 on 2020-03-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comorbidity',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='profile',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
        migrations.AddField(
            model_name='comorbidity',
            name='atendimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Atendimento'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='atendimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Atendimento'),
        ),
        migrations.AddField(
            model_name='trip',
            name='atendimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Atendimento'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='type',
            field=models.CharField(blank=True, choices=[('H', 'Doença cardíacas'), ('T', 'Hipertensão'), ('D', 'Diabetes'), ('E', 'Demência'), ('C', 'Bronquite crônica'), ('N', 'Câncer'), ('L', 'Doença crônica no fígado'), ('R', 'Doença renal crônica'), ('A', 'Asma'), ('P', 'Doença pulmonar crônica'), ('R', 'Doenças reumáticas'), ('O', 'Outra')], max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptom',
            field=models.CharField(choices=[('TR', 'Cansaço'), ('DI', 'Diarreia'), ('SB', 'Dificuldade respiratória'), ('ST', 'Dor de garganta'), ('AP', 'Dores no corpo'), ('FV', 'Febre'), ('DC', 'Tosse'), ('RN', 'Nariz escorrendo'), ('DI', 'Náusea'), ('OT', 'Outro')], default='', max_length=2, verbose_name='Tipo de sintoma'),
        ),
    ]
