# Generated by Django 2.2.3 on 2020-03-26 23:45

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20200326_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='smoke',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sus_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='cns',
            field=models.CharField(blank=True, default='000000000000000', max_length=15, verbose_name='Cartão do SUS'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_document',
            field=models.CharField(blank=True, default='000000000', max_length=9, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoker',
            field=models.BooleanField(blank=True, default=False, verbose_name='Fumante'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default='1970-01-01', verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, default='00000000000', max_length=9, validators=[validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não quer declarar')], default='', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptom',
            field=models.CharField(choices=[('CA', 'Cansaço'), ('DI', 'Diarreia'), ('SB', 'Dificuldade respiratória'), ('ST', 'Dor de garganta'), ('AP', 'Dores no corpo'), ('DC', 'Dor de cabeça'), ('FV', 'Febre'), ('TS', 'Tosse seca'), ('TP', 'Tosse produtiva'), ('FA', 'Falta de apetite'), ('CN', 'Congestão nasal'), ('RN', 'Nariz escorrendo'), ('NA', 'Náusea'), ('VO', 'Vômitos')], default='', max_length=2, verbose_name='Tipo de sintoma'),
        ),
    ]
