# Generated by Django 2.2.3 on 2020-03-27 13:28

import bitfield.models
import django.core.validators
from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20200326_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='asthma',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bronchitis',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cancer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chronic_kidney_disease',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chronic_liver_disease',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chronic_lung_disease',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dementia',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='heart_diseases',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hypertension',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='obesity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rheumatic_diseases',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='suspect',
            field=models.BooleanField(default=False, verbose_name='Suspeito de COVID-19'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='virus_exposure',
            field=bitfield.models.BitField([('confirmed_cases', 'Contato com casos confirmados'), ('suspect_cases', 'Contato com casos suspeitos'), ('foreign', 'Contato com pessoas que estiveram em locais com casos confirmados')], blank=True, default=0, verbose_name='Exposição COVID-19'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comorbidities',
            field=bitfield.models.BitField([('Y', 'Artrite reumatóide'), ('A', 'Asma'), ('C', 'Bronquite crônica'), ('N', 'Câncer'), ('E', 'Demência'), ('D', 'Diabetes'), ('H', 'Doença cardíacas'), ('L', 'Doença crônica no fígado'), ('R', 'Doença renal crônica'), ('R', 'Doenças reumáticas'), ('P', 'Doença pulmonar crônica'), ('I', 'Imunosuprimido'), ('T', 'Hipertensão'), ('V', 'HIV+'), ('B', 'Obesidade'), ('U', 'Portador de Lúpus')], default=0, verbose_name='Comorbidades'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default='1970-01-01', validators=[validators.prevent_future_date], verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, default='00000000000', max_length=11, validators=[validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não quer declarar')], default='', max_length=1, verbose_name='Sexo biológico'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='onset',
            field=models.DateField(blank=True, null=True, validators=[validators.prevent_future_date], verbose_name='Data do surgimento'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptom',
            field=models.CharField(choices=[('CA', 'Cansaço'), ('CN', 'Congestão nasal'), ('DI', 'Diarreia'), ('SB', 'Dificuldade respiratória'), ('ST', 'Dor de garganta'), ('DC', 'Dor de cabeça'), ('AP', 'Dores no corpo'), ('FA', 'Falta de apetite'), ('FV', 'Febre'), ('RN', 'Nariz escorrendo'), ('NA', 'Náusea'), ('TP', 'Tosse produtiva'), ('TS', 'Tosse seca'), ('VO', 'Vômitos')], default='', max_length=2, verbose_name='Tipo de sintoma'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(blank=True, default=None, null=True, validators=[validators.prevent_future_date], verbose_name='Ida'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_date',
            field=models.DateField(blank=True, default=None, null=True, validators=[validators.prevent_future_date], verbose_name='Volta'),
        ),
    ]
