# Generated by Django 2.2.3 on 2020-03-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20200327_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='tested',
            field=models.BooleanField(blank=True, default=False, verbose_name='Já foi testado'),
        ),
    ]
