# Generated by Django 2.2.3 on 2020-03-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_monitoring_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='result',
            field=models.CharField(choices=[('SR', 'Sem resposta'), ('P', 'Positivo'), ('N', 'Negativo')], default='S', max_length=1, verbose_name='Resultado do exame'),
        ),
    ]
