# Generated by Django 2.2.3 on 2020-03-27 14:22

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_auto_20200327_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='result',
            field=models.CharField(choices=[('SR', 'Sem resposta'), ('PO', 'Positivo'), ('NE', 'Negativo')], default='SR', max_length=2, verbose_name='Resultado do exame'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comorbidities',
            field=bitfield.models.BitField([('Y', 'Artrite reumatóide'), ('A', 'Asma'), ('C', 'Bronquite crônica'), ('N', 'Câncer'), ('E', 'Demência'), ('D', 'Diabetes'), ('H', 'Doença cardíacas'), ('L', 'Doença crônica no fígado'), ('R', 'Doença renal crônica'), ('W', 'Doenças reumáticas'), ('P', 'Doença pulmonar crônica'), ('I', 'Imunosuprimido'), ('T', 'Hipertensão'), ('V', 'HIV+'), ('B', 'Obesidade'), ('U', 'Portador de Lúpus')], default=0, verbose_name='Comorbidades'),
        ),
    ]
